# ===================== AIRFLOW BASE =====================
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: de_airflow:latest
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres/airflow_db
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags
    - ./src:/opt/airflow/src
    - ./pipelines:/opt/airflow/pipelines
    - ./observability:/opt/airflow/observability
    - logs_data_clinical:/opt/airflow/logs
  networks:
    - de-clinical

services:

  # ===================== MINIO =====================
  minio:
    image: minio/minio:latest
    container_name: de_healthcare_minio
    command: server /data --console-address ":9002"
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
      - logs_data_clinical:/var/log/minio
    networks:
      - de-clinical

  # ===================== POSTGRES =====================
  postgres:
    image: postgres:16
    container_name: de_healthcare_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - logs_data_clinical:/var/log/postgres
    networks:
      - de-clinical

  # ===================== AIRFLOW INIT =====================
  airflow-init:
    <<: *airflow-common
    container_name: de_airflow_init
    depends_on:
      - postgres
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create \
      --username admin \
      --password admin \
      --firstname admin \
      --lastname admin \
      --role Admin \
      --email admin@example.com || true"
    restart: "no"

  # ===================== AIRFLOW WEBSERVER =====================
  airflow-webserver:
    <<: *airflow-common
    container_name: de_airflow_webserver
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    command: airflow webserver

  # ===================== AIRFLOW SCHEDULER =====================
  airflow-scheduler:
    <<: *airflow-common
    container_name: de_airflow_scheduler
    depends_on:
      - airflow-init
    command: airflow scheduler

# ===================== NETWORK =====================
networks:
  de-clinical:
    name: de-clinical
    driver: bridge

# ===================== VOLUMES =====================
volumes:
  minio_data:
  postgres_data:
  logs_data_clinical: