[mypy]

; Mypy config file for ChurnPrediction API
files= trainer, api, main.py, runner.py

; General settings
python_version = 3.12
ignore_missing_imports = True
disallow_untyped_defs = False
check_untyoed_defs = True
warn_unused_ignores = True
show_error_codes = True

; Ignore missing imports for specific libraries
[mypy-polars.*]
ignore_missing_imports = True
[mypy-SQLAlchemy.*]
ignore_missing_imports =True
[mypy-pandas.*]
ignore_missing_imports = True
[mypy-apache-airflow.*]
ignore_missing_imports = True
; [mypy-numpy.*]
; ignore_missing_imports = True
[mypy-pydantic_settings.*]
ignore_missing_imports = True
[mypy-python_json_logger.*]
ignore_missing_imports = True